CREATE DATABASE IF NOT EXISTS SIMS2;
USE SIMS2;

CREATE TABLE Users(
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(255) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL
);

CREATE TABLE Spare_part(
SpId INT PRIMARY KEY AUTO_INCREMENT,
Name Varchar(200) NOT NULL,
Quantity INT NOT NULL,
UnitPrice INT NOT NULL,
TotalPrice INT NOT NULL

);


CREATE TABLE Stock_In(
Stock_in_id INT PRIMARY KEY AUTO_INCREMENT,
StockInQuantity INT NOT NULL,
StockInDate DATE NOT NULL,
SpId INT,
FOREIGN KEY (SpId) REFERENCES Spare_part(SpId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Stock_Out(
Stock_out_id INT PRIMARY KEY AUTO_INCREMENT,
StockOutQuantity INT NOT NULL,
StockOutDate DATE NOT NULL,
SpId INT,
StockOutUnitPrice INT NOT NULL,
StockOutTotalPrice INT NOT NULL,
FOREIGN KEY (SpId) REFERENCES Spare_part(SpId) ON DELETE CASCADE ON UPDATE CASCADE
);